//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCardProxyService.MyServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/HealthCardWcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServiceProxy.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        HealthCardProxyService.MyServiceProxy.CompositeType GetDataUsingDataContract(HealthCardProxyService.MyServiceProxy.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/StopReg", ReplyAction="http://tempuri.org/IService1/StopRegResponse")]
        HisCommon.DataEntity.Platform_StopReg_OutParamInfo StopReg(HisCommon.DataEntity.Platform_StopReg_InParam inParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CancelRegByHis", ReplyAction="http://tempuri.org/IService1/CancelRegByHisResponse")]
        HisCommon.DataEntity.Platform_CancelRegByHIS_OutParamInfo CancelRegByHis(HisCommon.DataEntity.Platform_CancelRegByHIS_InParam inParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RefundByHis", ReplyAction="http://tempuri.org/IService1/RefundByHisResponse")]
        HisCommon.DataEntity.Platform_RefundByHIS_OutParamInfo RefundByHis(HisCommon.DataEntity.Platform_RefundByHIS_InParam inParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintRegByHis", ReplyAction="http://tempuri.org/IService1/PrintRegByHisResponse")]
        HisCommon.DataEntity.Platform_PrintRegByHIS_OutParamInfo PrintRegByHis(HisCommon.DataEntity.Platform_PrintRegByHIS_InParam inParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PayRegByHis", ReplyAction="http://tempuri.org/IService1/PayRegByHisResponse")]
        HisCommon.DataEntity.Platform_PayRegByHIS_OutParamInfo PayRegByHis(HisCommon.DataEntity.Platform_PayRegByHIS_InParam inParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/QueryRegRefund", ReplyAction="http://tempuri.org/IService1/QueryRegRefundResponse")]
        HisCommon.DataEntity.Platform_QueryRegRefund_OutParamInfo QueryRegRefund(HisCommon.DataEntity.Platform_QueryRegRefund_InParam inParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RefundPay", ReplyAction="http://tempuri.org/IService1/RefundPayResponse")]
        HisCommon.DataEntity.Platform_RefundPay_OutParamInfo RefundPay(HisCommon.DataEntity.Platform_RefundPay_InParam inParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/QueryPayRefund", ReplyAction="http://tempuri.org/IService1/QueryPayRefundResponse")]
        HisCommon.DataEntity.Platform_QueryPayRefund_OutParamInfo QueryPayRefund(HisCommon.DataEntity.Platform_QueryPayRefund_InParam inParam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PushInfo", ReplyAction="http://tempuri.org/IService1/PushInfoResponse")]
        HisCommon.DataEntity.Platform_PushInfo_OutParam PushInfo(HisCommon.DataEntity.Platform_PushInfo_InParam inParam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HealthCardProxyService.MyServiceProxy.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HealthCardProxyService.MyServiceProxy.IService1>, HealthCardProxyService.MyServiceProxy.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public HealthCardProxyService.MyServiceProxy.CompositeType GetDataUsingDataContract(HealthCardProxyService.MyServiceProxy.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public HisCommon.DataEntity.Platform_StopReg_OutParamInfo StopReg(HisCommon.DataEntity.Platform_StopReg_InParam inParam) {
            return base.Channel.StopReg(inParam);
        }
        
        public HisCommon.DataEntity.Platform_CancelRegByHIS_OutParamInfo CancelRegByHis(HisCommon.DataEntity.Platform_CancelRegByHIS_InParam inParam) {
            return base.Channel.CancelRegByHis(inParam);
        }
        
        public HisCommon.DataEntity.Platform_RefundByHIS_OutParamInfo RefundByHis(HisCommon.DataEntity.Platform_RefundByHIS_InParam inParam) {
            return base.Channel.RefundByHis(inParam);
        }
        
        public HisCommon.DataEntity.Platform_PrintRegByHIS_OutParamInfo PrintRegByHis(HisCommon.DataEntity.Platform_PrintRegByHIS_InParam inParam) {
            return base.Channel.PrintRegByHis(inParam);
        }
        
        public HisCommon.DataEntity.Platform_PayRegByHIS_OutParamInfo PayRegByHis(HisCommon.DataEntity.Platform_PayRegByHIS_InParam inParam) {
            return base.Channel.PayRegByHis(inParam);
        }
        
        public HisCommon.DataEntity.Platform_QueryRegRefund_OutParamInfo QueryRegRefund(HisCommon.DataEntity.Platform_QueryRegRefund_InParam inParam) {
            return base.Channel.QueryRegRefund(inParam);
        }
        
        public HisCommon.DataEntity.Platform_RefundPay_OutParamInfo RefundPay(HisCommon.DataEntity.Platform_RefundPay_InParam inParam) {
            return base.Channel.RefundPay(inParam);
        }
        
        public HisCommon.DataEntity.Platform_QueryPayRefund_OutParamInfo QueryPayRefund(HisCommon.DataEntity.Platform_QueryPayRefund_InParam inParam) {
            return base.Channel.QueryPayRefund(inParam);
        }
        
        public HisCommon.DataEntity.Platform_PushInfo_OutParam PushInfo(HisCommon.DataEntity.Platform_PushInfo_InParam inParam) {
            return base.Channel.PushInfo(inParam);
        }
    }
}
