//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms测试.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Cloud.Xt.Soa.Hlht", ConfigurationName="ServiceReference1.APIServiceSoap")]
    public interface APIServiceSoap {
        
        // CODEGEN: 命名空间 Cloud.Xt.Soa.Hlht 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="Cloud.Xt.Soa.Hlht/HelloWorld", ReplyAction="*")]
        WindowsForms测试.ServiceReference1.HelloWorldResponse HelloWorld(WindowsForms测试.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Cloud.Xt.Soa.Hlht/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsForms测试.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WindowsForms测试.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 Cloud.Xt.Soa.Hlht 的元素名称 xml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="Cloud.Xt.Soa.Hlht/PubService", ReplyAction="*")]
        WindowsForms测试.ServiceReference1.PubServiceResponse PubService(WindowsForms测试.ServiceReference1.PubServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Cloud.Xt.Soa.Hlht/PubService", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsForms测试.ServiceReference1.PubServiceResponse> PubServiceAsync(WindowsForms测试.ServiceReference1.PubServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="Cloud.Xt.Soa.Hlht", Order=0)]
        public WindowsForms测试.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsForms测试.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="Cloud.Xt.Soa.Hlht", Order=0)]
        public WindowsForms测试.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsForms测试.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Cloud.Xt.Soa.Hlht")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PubServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PubService", Namespace="Cloud.Xt.Soa.Hlht", Order=0)]
        public WindowsForms测试.ServiceReference1.PubServiceRequestBody Body;
        
        public PubServiceRequest() {
        }
        
        public PubServiceRequest(WindowsForms测试.ServiceReference1.PubServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Cloud.Xt.Soa.Hlht")]
    public partial class PubServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public PubServiceRequestBody() {
        }
        
        public PubServiceRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PubServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PubServiceResponse", Namespace="Cloud.Xt.Soa.Hlht", Order=0)]
        public WindowsForms测试.ServiceReference1.PubServiceResponseBody Body;
        
        public PubServiceResponse() {
        }
        
        public PubServiceResponse(WindowsForms测试.ServiceReference1.PubServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="Cloud.Xt.Soa.Hlht")]
    public partial class PubServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PubServiceResult;
        
        public PubServiceResponseBody() {
        }
        
        public PubServiceResponseBody(string PubServiceResult) {
            this.PubServiceResult = PubServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIServiceSoapChannel : WindowsForms测试.ServiceReference1.APIServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIServiceSoapClient : System.ServiceModel.ClientBase<WindowsForms测试.ServiceReference1.APIServiceSoap>, WindowsForms测试.ServiceReference1.APIServiceSoap {
        
        public APIServiceSoapClient() {
        }
        
        public APIServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsForms测试.ServiceReference1.HelloWorldResponse WindowsForms测试.ServiceReference1.APIServiceSoap.HelloWorld(WindowsForms测试.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsForms测试.ServiceReference1.HelloWorldRequest inValue = new WindowsForms测试.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsForms测试.ServiceReference1.HelloWorldRequestBody();
            WindowsForms测试.ServiceReference1.HelloWorldResponse retVal = ((WindowsForms测试.ServiceReference1.APIServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsForms测试.ServiceReference1.HelloWorldResponse> WindowsForms测试.ServiceReference1.APIServiceSoap.HelloWorldAsync(WindowsForms测试.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsForms测试.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WindowsForms测试.ServiceReference1.HelloWorldRequest inValue = new WindowsForms测试.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WindowsForms测试.ServiceReference1.HelloWorldRequestBody();
            return ((WindowsForms测试.ServiceReference1.APIServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsForms测试.ServiceReference1.PubServiceResponse WindowsForms测试.ServiceReference1.APIServiceSoap.PubService(WindowsForms测试.ServiceReference1.PubServiceRequest request) {
            return base.Channel.PubService(request);
        }
        
        public string PubService(string xml) {
            WindowsForms测试.ServiceReference1.PubServiceRequest inValue = new WindowsForms测试.ServiceReference1.PubServiceRequest();
            inValue.Body = new WindowsForms测试.ServiceReference1.PubServiceRequestBody();
            inValue.Body.xml = xml;
            WindowsForms测试.ServiceReference1.PubServiceResponse retVal = ((WindowsForms测试.ServiceReference1.APIServiceSoap)(this)).PubService(inValue);
            return retVal.Body.PubServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsForms测试.ServiceReference1.PubServiceResponse> WindowsForms测试.ServiceReference1.APIServiceSoap.PubServiceAsync(WindowsForms测试.ServiceReference1.PubServiceRequest request) {
            return base.Channel.PubServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsForms测试.ServiceReference1.PubServiceResponse> PubServiceAsync(string xml) {
            WindowsForms测试.ServiceReference1.PubServiceRequest inValue = new WindowsForms测试.ServiceReference1.PubServiceRequest();
            inValue.Body = new WindowsForms测试.ServiceReference1.PubServiceRequestBody();
            inValue.Body.xml = xml;
            return ((WindowsForms测试.ServiceReference1.APIServiceSoap)(this)).PubServiceAsync(inValue);
        }
    }
}
